remote_theme: mikearnaldi/just-the-docs
search_enabled: true
aux_links:
  "Docs":
    - "//effect-ts.github.io/scrapelog"
  "API Reference":
    - "//effect-ts.github.io/scrapelog/docs/modules"
  "GitHub":
    - "//github.com/effect-ts/scrapelog"
